
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///mybatis
    username: root
    password: rose
  application:
    name: service-provider
mybatis:
  type-aliases-package: com.videostudy.springboot_2_user.pojo

  instance:
    lease-renewal-interval-in-seconds: 5 # 心跳时间
    lease-expiration-duration-in-seconds: 15 # 过期时间

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
server:
  port: 8081
